name: Update README Badges

on:
  push:
    paths:
      - '.github/badges/servers_badge_url.txt'
      - '.github/badges/users_badge_url.txt'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with Server Badge URL
        run: |
          SERVER_URL=$(cat .github/badges/servers_badge_url.txt)
          sed -i "s|!\[discordservers].*|!\[discordservers]($SERVER_URL)|" README.md

      - name: Update README with User Badge URL
        run: |
          USER_URL=$(cat .github/badges/users_badge_url.txt)
          sed -i "s|!\[discordusers].*|!\[discordusers]($USER_URL)|" README.md

      - name: Commit and Push if changed
        run: |
          git add README.md
          git diff --staged --quiet || git commit -m "Update README badges"
          git push