name: Update README Badges

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with Server Badge URL
        run: |
          SERVER_URL=$(cat .github/badges/servers_badge_url.txt)?style=for-the-badge
          sed -i "s|!\[discordservers].*|!\[discordservers]($SERVER_URL)|" README.md
        if: github.actor != 'github-actions[bot]'

      - name: Update README with 1-Day Uptime Badge URL
        run: |
          UPTIME_URL=$(cat .github/badges/1uptime_badge_url.txt)?style=for-the-badge
          sed -i "s|!\[1uptime].*|!\[1uptime]($UPTIME_URL)|" README.md

      - name: Update README with 7-Day Uptime Badge URL
        run: |
          UPTIME_URL=$(cat .github/badges/7uptime_badge_url.txt)?style=for-the-badge
          sed -i "s|!\[7uptime].*|!\[7uptime]($UPTIME_URL)|" README.md

      - name: Update README with 30-Day Uptime Badge URL
        run: |
          UPTIME_URL=$(cat .github/badges/30uptime_badge_url.txt)?style=for-the-badge
          sed -i "s|!\[30uptime].*|!\[30uptime]($UPTIME_URL)|" README.md

      - name: Update README with 365-Day Uptime Badge URL
        run: |
          UPTIME_URL=$(cat .github/badges/365uptime_badge_url.txt)?style=for-the-badge
          sed -i "s|!\[365uptime].*|!\[365uptime]($UPTIME_URL)|" README.md
      
      - name: Update README with User Badge URL
        run: |
          USER_URL=$(cat .github/badges/users_badge_url.txt)?style=for-the-badge
          sed -i "s|!\[discordusers].*|!\[discordusers]($USER_URL)|" README.md
        if: github.actor != 'github-actions[bot]'

      - name: Update README with Message Processed Badge URL
        run: |
          MESSAGE_URL=$(cat .github/badges/messagecount_badge_url.txt)?style=for-the-badge
          sed -i "s|!\[messageprocessed].*|!\[messageprocessed]($MESSAGE_URL)|" README.md

      - name: Update README with Last Updated Badge
        run: |
          DATE=$(date +"%Y-%m-%d %H:%M:%S")
          ENCODED_DATE=$(echo "$DATE" | sed -e 's| |%20|g' -e 's|:|%3A|g')
          BADGE_URL="https://img.shields.io/static/v1?label=Last%20Updated&message=${ENCODED_DATE}&color=blue&style=for-the-badge"
          # Make sure to escape special characters that might be interpreted by sed or shell
          ESCAPED_BADGE_URL=$(echo "$BADGE_URL" | sed -e 's|&|\\&|g')
          sed -i "s|!\[statslast\].*|!\[statslast\]($ESCAPED_BADGE_URL)|" README.md

      - name: Commit and Push if changed
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add README.md
          git diff --staged --quiet || git commit -m "Auto: Update README badges"
          git push
        if: github.actor != 'github-actions[bot]'
