name: Update README Badges

on: push

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with Server Badge URL
        run: |
          SERVER_URL=$(cat .github/badges/servers_badge_url.txt)?style=for-the-badge
          sed -i "s|!\[discordservers].*|!\[discordservers]($SERVER_URL)|" README.md
        if: github.actor != 'github-actions[bot]'
      
      - name: Update README with User Badge URL
        run: |
          USER_URL=$(cat .github/badges/users_badge_url.txt)?style=for-the-badge
          sed -i "s|!\[discordusers].*|!\[discordusers]($USER_URL)|" README.md
        if: github.actor != 'github-actions[bot]'

      - name: Commit and Push if changed
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add README.md
          git diff --staged --quiet || git commit -m "Update README badges"
          git push
        if: github.actor != 'github-actions[bot]'
